### create agent
POST http://localhost:5001/1/agents
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJhenVyYWkiLCJzdWIiOiIxIiwiYXVkIjoiZ2l0aHViIiwiZXhwIjoxNjkxNzc1MDM5Nzg2LCJpYXQiOjE2OTE3NzMyMzk3ODZ9.sRso19skSDyNyi01Pw64sA5ZcvtCpGjQHUcrd0izyT1erliGZmcdaQys7jVSDcmB8nEMwv-NcBl0xT1dj7juXZfEAgxfYN5Yq5_MavFb1_NaWSCrT5zKMBtdh2AfEXEmn7KUFIGpMlxKwA0jkwckknRtfGANjotNyavpPVRg3VW96k_jG3Edt77WNCXRktDrVMDtnPMOD7sex5Zv_qKYUELqtS3Rvd6Ak-iyWXK2Bser7Q6pNUIeDEMLEDP9cj8HXZhXtzF7n2DQ7Asf9Rl3dxk3bVVEYfv3vkGONqGwnc1j2kkSBvjgN9TMfl4lWfI-kB1GsKa5AHW9C1T7fnaAsDD2RUzjtelV18yTt_sqx8U4V8c8Ti0ObZULBbc0z_WOWKqdKn_s7h6MFlgloDpX8bPjgpncweADEOZzRAVmPBWxwFfYB9Vcquvy85Jm9H1-jlYmhxwmvVCECl-AnPgBIscFu5Wy2cysdXpDP1kAeyhTP3kQW6y_RES0TtZufkz28p94Mjqh2-wTue5dNT_OomniS8XTiDaSdZ2V0aE01s2adNDFKZYHbpnRWCCoglIJ5R-do1WQLA2ujNuqCLf4-5LEWsSC8h1T1PZlh9bzs9gKQFKomvhQ_jiyhVRuQUFiA5dwbGD7fS4Z4xKfCoIr6F6oITf1cWdDS-N9TI9QgFo
Content-Type: application/json

{
    "id": "id1",
    "name": "name1",
    "summary": "summary1",
    "params": {
        "model": "gpt-35-turbo"
    },
    "persona": "persona 1",
    "s": 1
}

### Update agent
PUT http://localhost:5001/1/agents
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJhenVyYWkiLCJzdWIiOiIxIiwiYXVkIjoiZ2l0aHViIiwiZXhwIjoxNjkxNzc1MDM5Nzg2LCJpYXQiOjE2OTE3NzMyMzk3ODZ9.sRso19skSDyNyi01Pw64sA5ZcvtCpGjQHUcrd0izyT1erliGZmcdaQys7jVSDcmB8nEMwv-NcBl0xT1dj7juXZfEAgxfYN5Yq5_MavFb1_NaWSCrT5zKMBtdh2AfEXEmn7KUFIGpMlxKwA0jkwckknRtfGANjotNyavpPVRg3VW96k_jG3Edt77WNCXRktDrVMDtnPMOD7sex5Zv_qKYUELqtS3Rvd6Ak-iyWXK2Bser7Q6pNUIeDEMLEDP9cj8HXZhXtzF7n2DQ7Asf9Rl3dxk3bVVEYfv3vkGONqGwnc1j2kkSBvjgN9TMfl4lWfI-kB1GsKa5AHW9C1T7fnaAsDD2RUzjtelV18yTt_sqx8U4V8c8Ti0ObZULBbc0z_WOWKqdKn_s7h6MFlgloDpX8bPjgpncweADEOZzRAVmPBWxwFfYB9Vcquvy85Jm9H1-jlYmhxwmvVCECl-AnPgBIscFu5Wy2cysdXpDP1kAeyhTP3kQW6y_RES0TtZufkz28p94Mjqh2-wTue5dNT_OomniS8XTiDaSdZ2V0aE01s2adNDFKZYHbpnRWCCoglIJ5R-do1WQLA2ujNuqCLf4-5LEWsSC8h1T1PZlh9bzs9gKQFKomvhQ_jiyhVRuQUFiA5dwbGD7fS4Z4xKfCoIr6F6oITf1cWdDS-N9TI9QgFo
Content-Type: application/json

{
    "id": "id1",
    "params": {
        "model": "gpt-35-turbo"
    },
    "persona": "persona-2",
    "s": 1
}

### get agents
GET http://localhost:5001/1/agents
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJhenVyYWkiLCJzdWIiOiIxIiwiYXVkIjoiZ2l0aHViIiwiZXhwIjoxNjkxNzc1MDM5Nzg2LCJpYXQiOjE2OTE3NzMyMzk3ODZ9.sRso19skSDyNyi01Pw64sA5ZcvtCpGjQHUcrd0izyT1erliGZmcdaQys7jVSDcmB8nEMwv-NcBl0xT1dj7juXZfEAgxfYN5Yq5_MavFb1_NaWSCrT5zKMBtdh2AfEXEmn7KUFIGpMlxKwA0jkwckknRtfGANjotNyavpPVRg3VW96k_jG3Edt77WNCXRktDrVMDtnPMOD7sex5Zv_qKYUELqtS3Rvd6Ak-iyWXK2Bser7Q6pNUIeDEMLEDP9cj8HXZhXtzF7n2DQ7Asf9Rl3dxk3bVVEYfv3vkGONqGwnc1j2kkSBvjgN9TMfl4lWfI-kB1GsKa5AHW9C1T7fnaAsDD2RUzjtelV18yTt_sqx8U4V8c8Ti0ObZULBbc0z_WOWKqdKn_s7h6MFlgloDpX8bPjgpncweADEOZzRAVmPBWxwFfYB9Vcquvy85Jm9H1-jlYmhxwmvVCECl-AnPgBIscFu5Wy2cysdXpDP1kAeyhTP3kQW6y_RES0TtZufkz28p94Mjqh2-wTue5dNT_OomniS8XTiDaSdZ2V0aE01s2adNDFKZYHbpnRWCCoglIJ5R-do1WQLA2ujNuqCLf4-5LEWsSC8h1T1PZlh9bzs9gKQFKomvhQ_jiyhVRuQUFiA5dwbGD7fS4Z4xKfCoIr6F6oITf1cWdDS-N9TI9QgFo


### get agent
GET http://localhost:5001/1/agents/id1
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJhenVyYWkiLCJzdWIiOiIxIiwiYXVkIjoiZ2l0aHViIiwiZXhwIjoxNjkxNzc1MDM5Nzg2LCJpYXQiOjE2OTE3NzMyMzk3ODZ9.sRso19skSDyNyi01Pw64sA5ZcvtCpGjQHUcrd0izyT1erliGZmcdaQys7jVSDcmB8nEMwv-NcBl0xT1dj7juXZfEAgxfYN5Yq5_MavFb1_NaWSCrT5zKMBtdh2AfEXEmn7KUFIGpMlxKwA0jkwckknRtfGANjotNyavpPVRg3VW96k_jG3Edt77WNCXRktDrVMDtnPMOD7sex5Zv_qKYUELqtS3Rvd6Ak-iyWXK2Bser7Q6pNUIeDEMLEDP9cj8HXZhXtzF7n2DQ7Asf9Rl3dxk3bVVEYfv3vkGONqGwnc1j2kkSBvjgN9TMfl4lWfI-kB1GsKa5AHW9C1T7fnaAsDD2RUzjtelV18yTt_sqx8U4V8c8Ti0ObZULBbc0z_WOWKqdKn_s7h6MFlgloDpX8bPjgpncweADEOZzRAVmPBWxwFfYB9Vcquvy85Jm9H1-jlYmhxwmvVCECl-AnPgBIscFu5Wy2cysdXpDP1kAeyhTP3kQW6y_RES0TtZufkz28p94Mjqh2-wTue5dNT_OomniS8XTiDaSdZ2V0aE01s2adNDFKZYHbpnRWCCoglIJ5R-do1WQLA2ujNuqCLf4-5LEWsSC8h1T1PZlh9bzs9gKQFKomvhQ_jiyhVRuQUFiA5dwbGD7fS4Z4xKfCoIr6F6oITf1cWdDS-N9TI9QgFo


### delete agent
DELETE http://localhost:5001/1/agents/id1
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJhenVyYWkiLCJzdWIiOiIxIiwiYXVkIjoiZ2l0aHViIiwiZXhwIjoxNjkxNzc1MDM5Nzg2LCJpYXQiOjE2OTE3NzMyMzk3ODZ9.sRso19skSDyNyi01Pw64sA5ZcvtCpGjQHUcrd0izyT1erliGZmcdaQys7jVSDcmB8nEMwv-NcBl0xT1dj7juXZfEAgxfYN5Yq5_MavFb1_NaWSCrT5zKMBtdh2AfEXEmn7KUFIGpMlxKwA0jkwckknRtfGANjotNyavpPVRg3VW96k_jG3Edt77WNCXRktDrVMDtnPMOD7sex5Zv_qKYUELqtS3Rvd6Ak-iyWXK2Bser7Q6pNUIeDEMLEDP9cj8HXZhXtzF7n2DQ7Asf9Rl3dxk3bVVEYfv3vkGONqGwnc1j2kkSBvjgN9TMfl4lWfI-kB1GsKa5AHW9C1T7fnaAsDD2RUzjtelV18yTt_sqx8U4V8c8Ti0ObZULBbc0z_WOWKqdKn_s7h6MFlgloDpX8bPjgpncweADEOZzRAVmPBWxwFfYB9Vcquvy85Jm9H1-jlYmhxwmvVCECl-AnPgBIscFu5Wy2cysdXpDP1kAeyhTP3kQW6y_RES0TtZufkz28p94Mjqh2-wTue5dNT_OomniS8XTiDaSdZ2V0aE01s2adNDFKZYHbpnRWCCoglIJ5R-do1WQLA2ujNuqCLf4-5LEWsSC8h1T1PZlh9bzs9gKQFKomvhQ_jiyhVRuQUFiA5dwbGD7fS4Z4xKfCoIr6F6oITf1cWdDS-N9TI9QgFo
