### Azurai GH Authorize (not in used, call gh endpoint directly
# @no-redirect
http://localhost:5001/1/accounts/github/authorize
?scope=repo%20project

### Azurai GH Get Token From Auth Code
POST http://localhost:5001/1/accounts/github/token
Content-Type: application/json

{
    "code":"3b44491dff2277e1d620851132c112edbf9c5f58"
}

### Azurai GH Get Token From Auth Code Options
options http://localhost:5001/1/accounts/github/token

### Signup
POST http://localhost:5001/1/accounts/signup
Content-Type: application/json

{
    "type": "github",
    "code": "x6hokltylz"
}