### Azurai GH Authorize
# @no-redirect
http://localhost:5001/1/accounts/github/authorize
?scope=user:email
&client_id={{$dotenv %GH_CLIENT_ID}}

### Azurai GH Get Token From Auth Code
POST http://localhost:5001/1/accounts/github/token
Content-Type: application/json

{
    "code":"3b44491dff2277e1d620851132c112edbf9c5f58"
}

### Azurai GH Get Token From Auth Code Options
options http://localhost:5001/1/accounts/github/token

### Signup
POST http://localhost:5001/1/accounts/signup
Content-Type: application/json

{
    "type": "confirm",
    "code": "x6hokltylz"
}