### Embed a repo
GET {{BACKEND}}/1/embed/ldarren/azurai/branches/main
Authorization: Bearer {{$dotenv %ACCESS_TOKEN}}
Content-Type: application/json

### create an embed db
POST {{BACKEND}}/1/embed/doc/ldarren/azurai/branches/main
Authorization: Bearer {{$dotenv %ACCESS_TOKEN}}
Content-Type: application/json

{
    "agent_id": 0,
    "contentType": "code",
    "targetAudience": "smart developer",
    "s": 1
}

### create an embed db
POST {{BACKEND}}/1/query
Authorization: Bearer {{$dotenv %ACCESS_TOKEN}}
Content-Type: application/json

{
    "content": "content of `.github` folder in the ldarren/azurai project?"
}