### Azurai GH Authorize
# @no-redirect
http://localhost:5001/1/accounts/github/authorize
?scope=user:email
&client_id={{$dotenv %GH_CLIENT_ID}}

### Azurai GH Get Token From Auth Code
POST http://localhost:5001/1/accounts/github/token
Content-Type: application/json

{
    "code":"3b44491dff2277e1d620851132c112edbf9c5f58"
}

### Azurai GH Get Token From Auth Code Options
options http://localhost:5001/1/accounts/github/token

###
GET https://api.github.com/user
Accept: application/vnd.github+json
Authorization: Bearer {{$dotenv %GH_ACCESS_TOKEN}}
'X-GitHub-Api-Version': 2022-11-28

### GH Authorize
# @no-redirect
https://github.com/login/oauth/authorize
?scope=user:email
&client_id={{$dotenv %GH_CLIENT_ID}}

### GH Get Token From Auth Code
POST https://github.com/login/oauth/access_token
Content-Type: application/x-www-form-urlencoded
User-Agent: azurai/0.1.0

client_id={{$dotenv %GH_CLIENT_ID}}
&client_secret={{$dotenv %GH_CLIENT_SECRET}}
&code=9162a00cd1b076a0f769
&accept=json

### GH Get Token From Refresh Token
POST https://github.com/login/oauth/access_token
Content-Type: application/x-www-form-urlencoded
User-Agent: azurai/0.1.0

client_id={{$dotenv %GH_CLIENT_ID}}
&client_secret={{$dotenv %GH_CLIENT_SECRET}}
&grant_type=refresh_token
&refresh_token={{$dotenv %GH_REFRESH_TOKEN}}
&accept=json
