### Get Model List
GET https://api.openai.com/v1/models
Authorization: Bearer {{$dotenv %OPENAI_API_KEY_DEV}}

### chat completion
# @prompt openai_api_key
POST https://api.openai.com/v1/chat/completions
Authorization: Bearer {{openai_api_key}}
Content-Type: application/json

{
    "model":"gpt-3.5-turbo-0613",
    "messages": [
        {"role":"system", "content":"You are acting as a code documentation expert for a project called ldarren/azurai.\nBelow is the code from a file located at `ui/mod/Void.js`. Do not say \"this file is a part of the ldarren/azurai project\"."},
        {"role":"user", "content":"Write a detailed technical explanation of what this code does. \nFocus on the high-level purpose of the code and how it may be used in the larger project.\nInclude code examples where appropriate. Keep you response between 100 and 300 words. \nDO NOT RETURN MORE THAN 300 WORDS.\nOutput should be in markdown format.\nDo not just list the methods and classes in this file.code:return{\n\tdeps:{\n\t\ttpl:['file','<%=d.message%>'],\n\t\tinfo:['map',{message:'Empty'}]\n\t},\n\tcreate: function(deps){\n\t\tthis.el.innerHTML=deps.tpl(deps.info)\n\t}\n}\n"}
    ]
}

### Source Code Extraction
POST https://api.openai.com/v1/chat/completions
Authorization: Bearer {{$dotenv %OPENAI_API_KEY_DEV}}
Content-Type: application/json

{
    "model":"gpt-3.5-turbo-0613",
    "messages": [
        {"role":"system", "content":"You are a code documentation assistant.\nyou help extract all the exported entities, non-exported entities, imported entities and methods or properties used in a file. at the end of all extraction output 'DONE'."},
        {"role":"user", "content":"```js\nconst path = require('node:path')\nmodule.exports = {\njoin(arr){return path.join(...arr)}\n}```"},
        {"role": "assistant", "content": null, "function_call": {
          "name": "exported_entity",
          "arguments": "{\n  \"entity_name\": \"join\",\n  \"entity_method_names\": [\"path.join\"]\n}"
        }},
        {"role": "user", "content": "continue"},
        {"role": "assistant", "content": null, "function_call": {
          "name": "imported_entity",
          "arguments": "{\n  \"entity_name\": \"path\",\n  \"entity_method_names\": [\"join\"]\n}"
        }},
        {"role": "user", "content": "continue"}
    ],
    "functions": [
        {
            "name": "exported_entity",
            "description": "document an exported entity with entity name, entity methos or properties used",
            "parameters": {
                "type": "object",
                "properties": {
                    "entity_name": {
                        "type": "string",
                        "description": "entity name"
                    },
                    "type": {
                        "type": "string",
                        "description": "entity name type",
                        "enum": ["class", "instance", "object", "function", "variable"]
                    },
                    "entity_method_names": {
                        "type": "array",
                        "description": "class or instance type entity method name, if sub-entity involved include whole path",
                        "items": {
                            "type": "string"
                        }
                    },
                    "entity_properties_names": {
                        "type": "array",
                        "description": "class or instance type entity properties name, if sub-entity involved include whole path",
                        "items": {
                            "type": "string"
                        }
                    }
                },
                "required": ["entity_name","type"]
            }
        },
        {
            "name": "non_exported_entity",
            "description": "document an non exported entity (or private entity) with entity name, entity methos or properties used",
            "parameters": {
                "type": "object",
                "properties": {
                    "entity_name": {
                        "type": "string",
                        "description": "entity name"
                    },
                    "type": {
                        "type": "string",
                        "description": "entity name type",
                        "enum": ["class", "instance", "object", "function", "variable"]
                    },
                    "entity_method_names": {
                        "type": "array",
                        "description": "class or instance type entity method name, if sub-entity involved include whole path",
                        "items": {
                            "type": "string"
                        }
                    },
                    "entity_properties_names": {
                        "type": "array",
                        "description": "class or instance type entity properties name, if sub-entity involved include whole path",
                        "items": {
                            "type": "string"
                        }
                    }
                },
                "required": ["entity_name", "type"]
            }
        },
        {
            "name": "imported_entity",
            "description": "document an imported entity (or private entity) with entity name, entity methods or properties used",
            "parameters": {
                "type": "object",
                "properties": {
                    "entity_name": {
                        "type": "string",
                        "description": "entity name"
                    },
                    "entity_method_names": {
                        "type": "array",
                        "description": "entity method name, if sub-entity involved include whole path",
                        "items": {
                            "type": "string"
                        }
                    },
                    "entity_properties_names": {
                        "type": "array",
                        "description": "entity properties name, if sub-entity involved include whole path",
                        "items": {
                            "type": "string"
                        }
                    }
                },
                "required": ["entity_name"]
            }
        }
    ]
}

### Use Chat Completion for Translation
POST https://api.openai.com/v1/chat/completions
Authorization: Bearer {{$dotenv %OPENAI_API_KEY_DEV}}
Content-Type: application/json

{
    "model":"gpt-4-1106-preview",
    "messages": [
        {"role":"system", "content":"You are a translator"},
        {"role":"user", "content":"translate this to english\n```桃花塢裡桃花庵，桃花庵下桃花仙。\n桃花仙人種桃樹，又摘桃花賣酒錢。\n酒醒只在花前坐，酒醉還來花下眠。\n半醒半醉日復日，花落花開年復年。\n但願老死花酒間，不願鞠躬車馬前。\n車塵馬足富者趣，酒盞花枝貧者緣。\n若將富貴比貧賤，一在平地一在天。\n若將貧賤比車馬，他得驅馳我得閒。\n別人笑我太瘋癲，我笑他人看不穿。\n不見五陵豪傑墓，無花無酒鋤作田。```"},
        {"role": "assistant","content": "In Peach Blossom Hut lies Peach Blossom Hermitage, beneath which dwells the Peach Blossom Immortal. \nThe Peach Blossom Immortal plants peach trees, picks their blossoms to sell for wine money. \nAwake, he sits before the flowers; drunk, he sleeps beneath them too. \nDay by day, half-sober, half-drunk; year by year, as flowers fall and bloom anew. \nHe simply wishes to die amidst wine and flowers, with no desire to bow before the wealthy's carriages. \nCarriages and horses kick up dust—it’s the pursuit of the rich; wine cups and flower branches are the lot of the poor. \nIf we compare riches to poverty, one is on the ground, the other soars to the heavens. \nIf we compare poverty to carriages and horses, they have the drive, while I have leisure. \nOthers mock me for being overly mad; I laugh at them, unseen through their opaque view. \nThey fail to see the graves of the eminent and mighty; without flowers, without wine, they plow the fields."},
        {"role":"user", "content":"`無花無酒鋤作田` should it be translated as the graves have no flowers and wine and had been plow to farm fields?"},
        {"role": "assistant","content": "Yes, the line `無花無酒鋤作田` suggests that the graves of once-great individuals, who no longer receive flowers or wine in tribute or remembrance, are now forgotten and reclaimed by the land to be plowed like ordinary fields. The presence of flowers and wine at a grave typically indicates that the person buried there was honored and remembered. The absence of these tributes and the act of plowing indicate that the person has been forgotten, and the land is simply being used for agriculture, stripping away any former glory.\n\nSo, the more contextually accurate translation for `無花無酒鋤作田` would be, \"The graves of the mighty lack flowers and wine; they're now just fields to be plowed.\""},
        {"role":"user","content": "please update the translation"}
    ]
}