###
# @prompt openai_api_key
GET https://api.openai.com/v1/models
Authorization: Bearer {{openai_api_key}}

### chat completion
# @prompt openai_api_key
POST https://api.openai.com/v1/chat/completions
Authorization: Bearer {{openai_api_key}}
Content-Type: application/json

{
    "model":"gpt-3.5-turbo-0613",
    "messages": [
        {"role":"system", "content":"You are acting as a code documentation expert for a project called ldarren/azurai.\nBelow is the code from a file located at `ui/mod/Void.js`. Do not say \"this file is a part of the ldarren/azurai project\"."},
        {"role":"user", "content":"Write a detailed technical explanation of what this code does. \nFocus on the high-level purpose of the code and how it may be used in the larger project.\nInclude code examples where appropriate. Keep you response between 100 and 300 words. \nDO NOT RETURN MORE THAN 300 WORDS.\nOutput should be in markdown format.\nDo not just list the methods and classes in this file.code:return{\n\tdeps:{\n\t\ttpl:['file','<%=d.message%>'],\n\t\tinfo:['map',{message:'Empty'}]\n\t},\n\tcreate: function(deps){\n\t\tthis.el.innerHTML=deps.tpl(deps.info)\n\t}\n}\n"}
    ]
}